# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cls < Formula
  desc "CLI for querying Console Log Server logs"
  homepage "https://github.com/kooler/ConsoleLogServer"
  version "1.0.0"
  license "O'Saasy License Agreement"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kooler/ConsoleLogServer/releases/download/v1.0.0/cls_1.0.0_darwin_amd64.tar.gz"
      sha256 "9759411543f66352caf230b73759a64f427445657dc61114356e5162a17ead41"

      define_method(:install) do
        bin.install "cls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kooler/ConsoleLogServer/releases/download/v1.0.0/cls_1.0.0_darwin_arm64.tar.gz"
      sha256 "55bdd04383795043430b3546c56a720f0701faf1d998a90069896d9b091306fe"

      define_method(:install) do
        bin.install "cls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/ConsoleLogServer/releases/download/v1.0.0/cls_1.0.0_linux_amd64.tar.gz"
      sha256 "37329732107c787046fa0c943408cd7a932a645c2ea38127685d93106fc304e0"
      define_method(:install) do
        bin.install "cls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/ConsoleLogServer/releases/download/v1.0.0/cls_1.0.0_linux_arm64.tar.gz"
      sha256 "94161f51b48966789cfbd2460925fd60fdb78a4a90ee51297b2789cf5b6f8a25"
      define_method(:install) do
        bin.install "cls"
      end
    end
  end

  test do
    system "#{bin}/cls", "-version"
  end
end
