# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cls < Formula
  desc "CLI for querying Console Log Server logs"
  homepage "https://github.com/kooler/ConsoleLogServer"
  version "1.0.1"
  license "O'Saasy License Agreement"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kooler/ConsoleLogServer/releases/download/v1.0.1/cls_1.0.1_darwin_amd64.tar.gz"
      sha256 "9e94023a974a72328c5b1ec737823248e9755f249f00e385236f00bd92d4a322"

      define_method(:install) do
        bin.install "cls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kooler/ConsoleLogServer/releases/download/v1.0.1/cls_1.0.1_darwin_arm64.tar.gz"
      sha256 "86c73b88d9e5054e4d26999fcb598ee26d416471a6b09d9e1d80f8a6c141dc66"

      define_method(:install) do
        bin.install "cls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/ConsoleLogServer/releases/download/v1.0.1/cls_1.0.1_linux_amd64.tar.gz"
      sha256 "634315896022ddf35ec3ab46af17ff08ecfe88e7b3cd7ab275d4a0a20c5434b3"
      define_method(:install) do
        bin.install "cls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/ConsoleLogServer/releases/download/v1.0.1/cls_1.0.1_linux_arm64.tar.gz"
      sha256 "de316b3f85fce13645ce6361edc9e5d55429bf30fe4779395782c8be60d4e29e"
      define_method(:install) do
        bin.install "cls"
      end
    end
  end

  test do
    system "#{bin}/cls", "-version"
  end
end
