# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Middaycommander < Formula
  desc "A modern dual-panel terminal file manager"
  homepage "https://github.com/kooler/MiddayCommander"
  version "0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.6/MiddayCommander_0.6_darwin_amd64.tar.gz"
      sha256 "6637ea1078f96b2b24060e7a8a25a224cd5a22105cecceafcef1847e0c46effe"

      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.6/MiddayCommander_0.6_darwin_arm64.tar.gz"
      sha256 "0f94b29c8561ff45534206cecbe191c481b50ee1c16a596a9b7b8549bf8d943a"

      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.6/MiddayCommander_0.6_linux_amd64.tar.gz"
      sha256 "7fed353734fd2b181535c9a4d3aaf25e9a46e0f1742cc1cb679926d205ff7a22"
      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.6/MiddayCommander_0.6_linux_arm64.tar.gz"
      sha256 "102b2cd1bd620362212be3ac6dbe94f506fe613b1e7b46028530abb4322f215c"
      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  test do
    system "#{bin}/mdc", "--version"
  end
end
