# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Middaycommander < Formula
  desc "A modern dual-panel terminal file manager"
  homepage "https://github.com/kooler/MiddayCommander"
  version "0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.12/MiddayCommander_0.12_darwin_amd64.tar.gz"
      sha256 "8bb91f5d247a3b72e81c9924f8fefef83a8f7a64ca971879a92ba74cbd6915ce"

      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.12/MiddayCommander_0.12_darwin_arm64.tar.gz"
      sha256 "a41538b2a6c9b4c59647e59163dc0d8552e203f016b04c9754659aa699a2cd1b"

      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.12/MiddayCommander_0.12_linux_amd64.tar.gz"
      sha256 "0fcd158c26341fe729c9214824d04478ca3d9de7b458ee81c27bbd0151781a66"
      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.12/MiddayCommander_0.12_linux_arm64.tar.gz"
      sha256 "6c30ce60907ba2d07e2a237e7784f45ed07ed0f65e89e6e5c133e80f0c2d3507"
      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  test do
    system "#{bin}/mdc", "--version"
  end
end
