# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Middaycommander < Formula
  desc "A modern dual-panel terminal file manager"
  homepage "https://github.com/kooler/MiddayCommander"
  version "0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.3/MiddayCommander_0.3_darwin_amd64.tar.gz"
      sha256 "4895040cc805d19ab64295138c4b91aa40e449ebfb865d723a552da085e1784b"

      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.3/MiddayCommander_0.3_darwin_arm64.tar.gz"
      sha256 "53c503ec28925520718bf4018a8af790ab48fefdc9838b31f2b541178fee0a31"

      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.3/MiddayCommander_0.3_linux_amd64.tar.gz"
      sha256 "894b5a4472b86df4cd298a094d076a7c723c4e6b5df4ffcbe0b9a01ca78131b8"
      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.3/MiddayCommander_0.3_linux_arm64.tar.gz"
      sha256 "9b9213eda024a4ec6d0d8eb57c3d9d77184c823cb902a1acf4c0b6de63e37f71"
      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  test do
    system "#{bin}/mdc", "--version"
  end
end
