# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Middaycommander < Formula
  desc "A modern dual-panel terminal file manager"
  homepage "https://github.com/kooler/MiddayCommander"
  version "0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.10/MiddayCommander_0.10_darwin_amd64.tar.gz"
      sha256 "c6714072bebd496e46ae28453151d5b8a49584212069f751e492ec723acf4305"

      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.10/MiddayCommander_0.10_darwin_arm64.tar.gz"
      sha256 "a3a584d536c27ebcfecdcf8b00a0dac9607cbe64f60ccbdf072e818fe1bd1270"

      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.10/MiddayCommander_0.10_linux_amd64.tar.gz"
      sha256 "cfe27507a7109bff73d0ed0fc0aae1bff7bffeef95e9fd34791196c58e487158"
      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.10/MiddayCommander_0.10_linux_arm64.tar.gz"
      sha256 "84fdba8e753a525bdc398ec5a28627237a7a53c52b7e4ee16026912ba7456385"
      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  test do
    system "#{bin}/mdc", "--version"
  end
end
