# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Middaycommander < Formula
  desc "A modern dual-panel terminal file manager"
  homepage "https://github.com/kooler/MiddayCommander"
  version "0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.7/MiddayCommander_0.7_darwin_amd64.tar.gz"
      sha256 "367c6977ba501450ca315613cd477dd71ef1c83c6eceaad1ce34a2b6e1cc2b79"

      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.7/MiddayCommander_0.7_darwin_arm64.tar.gz"
      sha256 "d45ec55ae1998e80659cea7f497eb7b20335f99ae1629307ac339d4fc5c9b87a"

      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.7/MiddayCommander_0.7_linux_amd64.tar.gz"
      sha256 "8af68f83a33a74e2c7e6876daf51fb20bdbf2b6a3dc18b426c418223ae2a3a8a"
      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kooler/MiddayCommander/releases/download/v0.7/MiddayCommander_0.7_linux_arm64.tar.gz"
      sha256 "a685c0954f2672175c979de936a20c0ac76fd2e13d210162f72b4adeeb1d8d41"
      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  oldnames "MiddayCommander"

  test do
    system "#{bin}/mdc", "--version"
  end
end
